language: go
sudo: false
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
before_install:
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - go test ./...
  - go test -c -covermode=count -coverpkg=github.com/sniperkit/gotests/pkg,github.com/sniperkit/gotests/pkg/input,github.com/sniperkit/gotests/pkg/render,github.com/sniperkit/gotests/pkg/goparser,github.com/sniperkit/gotests/pkg/output,github.com/sniperkit/gotests/pkg/models
  - ./gotests.test -test.coverprofile coverage.cov
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=coverage.cov
